# Generated by Django 3.0.7 on 2020-07-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nametg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
