# Generated by Django 3.0.7 on 2020-07-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_product_nametg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
