# Generated by Django 3.0.7 on 2020-07-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_product_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
